### ISSUE TITLE
请求添加“六”字

### ISSUE THREAD

**Issue by lxsq** [tobyxdd/chouxiang-dict#3]

**Comment by tobyxdd** [comment]
六感觉不是很常用啊，这里是和 666 的 6 一个意思么？

**Comment by lxsq** [comment]
> 六感觉不是很常用啊，这里是和 666 的 6 一个意思么？

类似十年前的“呵呵”，表达敷衍了事。
[https://www.bilibili.com/video/BV1pP4y1S7Lp/](6是什么梗【梗指南】)
